#! /usr/bin/csh

echo "Converting data..."
/usr/bin/nice -5 CIMIS_SFC_Converter.pl

if (-e ../output/cimis60.0qc.sort) rm ../output/cimis60.0qc.sort
echo "Sorting data..."
cosort Y2Kqcf_sort_spec <../output/cimis60.0qc > ../output/cimis60.0qc.sort

echo "Creating the dayfiles..."
/work/software/library/createdays/Version4_4digitYear/Y2Kcreate_day_files ../output/cimis60.0qc.sort ../final/CIMIS60_
