#! /usr/bin/csh

echo "Converting data..."
/usr/bin/nice -5 TREX_SFC_Converter.pl

if (-e ../output/trex05.0qc.sort) rm ../output/trex05.0qc.sort
echo "Sorting data..."
cosort Y2Kqcf_sort_spec <../output/trex05.0qc > ../output/trex05.0qc.sort

echo "Creating the dayfiles..."
/work/software/library/createdays/Version4_4digitYear/Y2Kcreate_day_files ../output/trex05.0qc.sort ../final/TREX05_
