#! /usr/bin/csh

echo "Converting data..."
/usr/bin/nice -5 GBUAPCD_SFC_Converter.pl

echo "Sorting data..."
if (-e ../output/gbuapcd60.0qc.sort) rm ../output/gbuapcd60.sort
cosort Y2Kqcf_sort_spec <../output/gbuapcd60.0qc > ../output/gbuapcd60.0qc.sort

echo "Creating the dayfiles..."
/work/software/library/createdays/Version4_4digitYear/Y2Kcreate_day_files ../output/gbuapcd60.0qc.sort ../final/GBUAPCD60_
