Data Type:                         CLASS/Ascending
Project ID:                        PECAN
Release Site Type/Site ID:         GREEN;Greensburg, KS
Release Location (lon,lat,alt):    999 00.00'E, 99 00.00'N, 999.000, 99.000, 999.0
UTC Release Time (y,m,d,h,m,s):    2015, 06, 06, 03:00:00
/
/
/
/
/
/
Nominal Release Time (y,m,d,h,m,s):2015, 06, 06, 03:00:00
 Time  Press  Temp  Dewpt  RH    Ucmp   Vcmp   spd   dir   Wcmp     Lon     Lat    Ele   Azi   Alt    Qp   Qt   Qrh  Qu   Qv   QdZ
  sec    mb     C     C     %     m/s    m/s   m/s   deg   m/s      deg     deg    deg   deg    m    code code code code code code
------ ------ ----- ----- ----- ------ ------ ----- ----- ----- -------- ------- ----- ----- ------- ---- ---- ---- ---- ---- ----
