#! /usr/bin/csh

echo "Converting data..."
/usr/bin/nice -5 ASU_SFC_Converter.pl

echo "Sorting data..."
cosort Y2Kqcf_sort_spec <../output/asusonic.0qc > ../output/asusonic.0qc.sort

echo "Creating the dayfiles..."
/work/software/library/createdays/Version4_4digitYear/Y2Kcreate_day_files ../output/asusonic.0qc.sort ../final/ASUsonic05_
