#! /usr/bin/csh

echo "Converting data..."
/usr/bin/nice -5 Hobo_SFC_Converter.pl

if (-e ../output/hobo.0qc.sort) rm ../output/hobo.0qc.sort
echo "Sorting data..."
cosort Y2Kqcf_sort_spec <../output/utah_hobo5.0qc > ../output/utah_hobo5.0qc.sort

echo "Creating the dayfiles..."
/work/software/library/createdays/Version4_4digitYear/Y2Kcreate_day_files ../output/utah_hobo5.0qc.sort ../final/UTAH_HOBO5_
