#! /usr/bin/csh

echo "Converting data..."
/usr/bin/nice -5 ChinaLakeHANDAR05_SFC_Converter.pl

if (-e ../output/chlkhand05.0qc.sort) rm ../output/chlkhand05.0qc.sort
echo "Sorting data..."
cosort Y2Kqcf_sort_spec <../output/chlkhand05.0qc > ../output/chlkhand05.0qc.sort

echo "Creating the dayfiles..."
/work/software/library/createdays/Version4_4digitYear/Y2Kcreate_day_files ../output/chlkhand05.0qc.sort ../final/CHINALAKE_HANDAR05_
