#! /bin/csh
#--------------------------------------------------------------
# Use the Ant build.xml file to make dayfiles. Not this script.
#--------------------------------------------------------------
if (!(-e ../database)) then
    mkdir ../database
endif

/net/work/dev/make_esc_dayfiles/make_esc_dayfiles ../final/*.cls ../database/ChinaLake_
