./fixtimes.pl FF01.nc
./fixtimes.pl FF02.nc
./fixtimes.pl RF01.nc
./fixtimes.pl RF03.nc
./fixtimes.pl RF04.nc
./fixtimes.pl RF05.nc
./fixtimes.pl RF06.nc
./fixtimes.pl RF07.nc
./fixtimes.pl RF08A.nc
./fixtimes.pl RF08B.nc
./fixtimes.pl RF09.nc
./fixtimes.pl RF10.nc
./fixtimes.pl RF11.nc
./fixtimes.pl RF12.nc
./fixtimes.pl RF13.nc
./fixtimes.pl RF14.nc
./fixtimes.pl RF15.nc
./fixtimes.pl RF16.nc
./fixtimes.pl RF17.nc
