#! /usr/bin/csh

echo "Converting data..."
/usr/bin/nice -5 DRI_SFC_Converter.pl

echo "Sorting data..."
cosort Y2Kqcf_sort_spec <../output/dri_aws05.0qc > ../output/dri_aws05.0qc.sort

echo "Creating the dayfiles..."
/work/software/library/createdays/Version4_4digitYear/Y2Kcreate_day_files ../output/dri_aws05.0qc.sort ../final/DRI_AWS05_
